openapi: 3.1.0
info:
  title: Quiz Generator API
  version: 1.0.0
servers:
  - url: https://jcamilogarciacano.github.io/gpt-quiz-action-demo
paths:
  /quiz:
    get:
      operationId: getQuiz
      summary: Get quiz questions for a specific topic
      parameters:
        - in: query
          name: topic
          required: true
          description: The subject of the quiz (e.g., photosynthesis, gravity)
          schema:
            type: string
      responses:
        '200':
          description: A quiz generated based on the topic
          content:
            application/json:
              schema:
                type: object
                properties:
                  topic:
                    type: string
                  questions:
                    type: array
                    items:
                      type: object
                      properties:
                        question:
                          type: string
                        answer:
                          type: string
        '404':
          description: Topic not found or invalid
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
